name = "pilihan-tka"
main = "_worker.js"
compatibility_date = "2024-09-28"
assets = { directory = "." }

# Binding Cloudflare D1 Database
[[d1_databases]]
binding = "DB"
database_name = "db-pilihan-tka"
database_id = "db-pilihan-tka"
